
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxepmnehppfiqumzsbwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZXBtbmVocHBmaXF1bXpzYndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDc1NjgsImV4cCI6MjA2MDU4MzU2OH0.HpyHF3XhvOiUqwH2-cwQLXE5itG14ojI-DnJ0p09PBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    debug: false, // Disable debug logging in production
  },
  global: {
    // Enable for better debugging visibility during development
    fetch: (...args) => {
      console.log('Supabase Fetch:', args[0]);
      return fetch(...args);
    },
  },
});

// Helper function to check if connection is working
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    console.log("Supabase connection check:", error ? "Failed" : "Success");
    console.log("Session status:", data.session ? "Active" : "No active session");
    return !error;
  } catch (e) {
    console.error("Supabase connection error:", e);
    return false;
  }
};

// Initialize connection check
checkSupabaseConnection();
